### PR TITLE
#31 Adds support for java lts 8 and 11

### PR DESCRIPTION
**Pull request by ryankazokas**
Builds with both current LTS versions of java 8 and 11.

### CODE REVIEW

**Comment by ryankazokas** [comment]
@rjdavis3 i'm building the pit test history file again. That's why the pr build failed.

**Comment by ryankazokas** [comment]
@rjdavis3 do you know how to turn off the logging that logs to standard out/error during the tests? These builds are failling due to excessive log output. I'm not totally sure that will fix it because i think we are bumping up against build times with travis but i'll give it a shot if you know of a way. I tried adding a lo4j properties file in the src/test/resources directory but no luck.

**Comment by rjdavis3** [comment]
@ryankazokas it's simple4j that is doing all of this. Turn it off within ShopifySdkTest class by doing this:

`	@BeforeClass
	public static void beforeClass() {
		System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "OFF");
	}
`

**Comment by rjdavis3** [comment]
@ryankazokas you can probably also try playing around with `timeoutConstant` in the pitest configuration to get the build to run quicker:
https://pitest.org/quickstart/maven/

**Comment by ryankazokas** [comment]
@rjdavis3 I've merged this with the changes for pagination. I don't think doing this in its own release is a necessity. If you think otherwise let me know and we can reopen this to go out by itself.

**Comment by ryankazokas** [comment]
Just for reference this is the PR that these changes are now in #34

**Pull request closed without merging**
